# Site settings
description: "code writer, software architect at @isetbr, open source lover, musician and writer in free hours."
# baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://www.devsdmf.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: devsdmf
user_description: "code writer, software architect at @isetbr, open source lover, musician and writer in free hours."
user_title: devSDMF
email: devsdmf@gmail.com
twitter_username:  devsdmf
github_username:   devsdmf
facebook_username: devsdmf
disqus_username:   devsdmf

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
